# Generated by Django 4.0.1 on 2022-01-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('cnt', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('intime', models.DateField()),
                ('location', models.CharField(choices=[('台北', 'Taipei'), ('屏東', 'Pingtung')], default='台北', max_length=10)),
                ('gender', models.CharField(choices=[('男', 'Male'), ('女', 'Female')], default='男', max_length=10)),
                ('is_check', models.BooleanField(default=True)),
                ('had_award', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='draw.department')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='draw.title')),
            ],
        ),
        migrations.CreateModel(
            name='AwardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awardlist', to='draw.employee')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awardlist', to='draw.prize')),
            ],
        ),
    ]
