# Generated by Django 4.0.1 on 2022-01-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_create_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='time_qlfy',
            field=models.IntegerField(default=0),
        ),
    ]
