# Generated by Django 4.0.1 on 2022-01-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_add_Prize_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
